### ISSUE TITLE
store_csv leaks s_handle->lents allocated at line 1516

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ldms#1073]
By inspection, no free for lents occurs, and by test valgrind agrees.

**Comment by tom95858** [comment]
@baallan, please fix?

**Comment by baallan** [comment]
see #1487 1487

**Comment by baallan** [comment]
fix in 445 need cherry pick to 451

**Comment by baallan** [comment]
see also #1502 for cherry pick to main.
