### ISSUE TITLE
`simple_lps.c` resets `ldmsd_stream_publish()`'s returned code variable and then checks the value

### ISSUE THREAD

**Issue by nichamon** [ovis-hpc/ldms#1095]
While I was investigating the stalled dist-check test, I found this. https://github.com/ovis-hpc/ovis/blob/46ab92012b8fee43dff0d2328b19c157ef49baa2/ldms/src/sampler/netlink/simple_lps.c#L1008

After the variable is set to 0, the program checks whether or not its value is zero. 
https://github.com/ovis-hpc/ovis/blob/46ab92012b8fee43dff0d2328b19c157ef49baa2/ldms/src/sampler/netlink/simple_lps.c#L1009

What is the objective of the check?

**Comment by baallan** [comment]
@nichamon the check is correct, but the reset of the checked result was to suppress a spurious error from string message publications at the time the test was written.

I am reinvestigating whether the spurious error has since been fixed.

**Comment by nichamon** [comment]
@baallan I'll wait for your result then.

**Comment by tom95858** [comment]
Please reopen if necessary.
