### ISSUE TITLE
transient sets aggregated with push=onchange not leaving L1 after deletion on L0

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ldms#1141]
The pid sampler (linux-proc-sampler) creates sets for pids it's notified of and clears these sets when the pid monitored goes away.  It appears that ~1/3 of these sets (388/1200) never get cleaned up on the L1 aggregator, even after 1300 seconds.

**Comment by baallan** [comment]
Will run more diagnostics to see if this looks a lot like #771 at the L1.

**Comment by baallan** [comment]
The symptom is repeatable, but a bit arbitrary, thusly:
- run pid sampler on 20 nodes.
- launch 36 ranks/node of mpiGraph using mpiexec or srun.
- job completes; tracked pids all gone.
- for 2 arbitrary (varies run to run which node) nodes, the 36 local pid-related sets are deleted by the sampler, but hang in the deleting state according to set_stats.
- Also for those same nodes, the messages that the pids are gone do not get delivered to the L1, even though all such messages are published at L0 before the corresponding set_deletes are performed. This is just plain weird and in fact all subsequent message deliveries (e.g. new pid appearance) on the same 2 nodes also do not reach L1.

**Comment by baallan** [comment]
It appears this issue has been resolved by #1153.

**Comment by baallan** [comment]
Actually, it's still found in further testing...

**Comment by nichamon** [comment]
@baallan Thanks for the info!

I assume that no L2 aggregated from L1.

**Comment by baallan** [comment]
> @baallan Thanks for the info!
> 
> I assume that no L2 aggregated from L1.

Correct

**Comment by nichamon** [comment]
@tom95858 

> Also for those same nodes, the messages that the pids are gone do not get delivered to the L1, even though all such messages are published at L0 before the corresponding set_deletes are performed. This is just plain weird and in fact all subsequent message deliveries (e.g. new pid appearance) on the same 2 nodes also do not reach L1.

This observation made me think that the root cause may not be related to the delete and push path. It is instead in the transport path. Did Ben and you reproduce this today? What do you think?

**Comment by baallan** [comment]
@nichamon with the new logging stuff, whats the syntax to turn on logging for just the transport (and maybe the set management) code but no sampler plugin logging?
or do  we still need a recompile with extra flags for transport?

**Comment by nichamon** [comment]
> @nichamon with the new logging stuff, whats the syntax to turn on logging for just the transport (and maybe the set management) code but no sampler plugin logging? or do we still need a recompile with extra flags for transport?

With the top of OVIS-4, everything is still the same regarding changing log levels. I'm incrementally creating patches of the refactored code. 

When all the refactored code is in the tree, you will do 'loglevel regex=xprt.* level=DEBUG' to turn on the DEBUG messages of all transport layers, i.e., ldmsd, ldms, and Zap.

**Comment by nichamon** [comment]
@baallan I'm making a patch and will create a pull request within 1-2 hours from now. I'll tag you when I have it for you to test.

**Comment by baallan** [comment]
@nichamon @tom95858 This problem also reproduces with qlogic InfiniPath_QLE7340 adapters on toss3, the hardware on our tlcc2 systems, so it's not just omnipath-specific rdma with the sets stuck in deleting mode. The dev system here with that hardware is called btaco. The version running is near the top of tree (sum 7dfaa).

**Comment by nichamon** [comment]
> @nichamon @tom95858 This problem also reproduces with qlogic InfiniPath_QLE7340 adapters on toss3, the hardware on our tlcc2 systems, so it's not just omnipath-specific rdma with the sets stuck in deleting mode. The dev system here with that hardware is called btaco. The version running is near the top of tree (sum 7dfaa).

@baallan Thanks for the info. I'll try to send a patch to you to get more diagnostic messages, or we can setup a session to work on it together, hopefully, next week.

**Comment by baallan** [comment]
@nichamon if you have a branch with more debugging stuff to try (possibly including additional -D flags at compile time), let me know.

**Comment by tom95858** [comment]
@nichamon where are we on this?

**Comment by nichamon** [comment]
> @nichamon where are we on this?

After detailed investigation including multiple gdb sessions with @baallan, we couldn't root cause the issue or reproduce it on our test beds with sock or rdma. @baallan confirmed in the email exchange with me that he didn't see the symptom when using sock.  While I suspect the cause lies in the transport layer rather than the delete path, the codebase has evolved significantly since then, particularly with Rails on how we handles connections between samplers and aggregators.

Since there haven't been any similar reports since 2023, I recommend closing this issue. We'll monitor for any recurrence and investigate with our updated codebase context if needed.

**Comment by baallan** [comment]
I have half a dozen issues including this one on a list to check the reproducibility of using stria and cts1x. both are now on redhat8/toss4 so the issue may have resolved itself it the problem is lower in the stack. will reopen if still present.
