### ISSUE TITLE
ldmsd_controller _Py_tracemalloc_config undefined on centos8/rhel8/toss4 

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ldms#1332]
Has anyone run into an error like the following? Can't run ldmsd_controller.
ldd doesn't turn up an unsatisfied libraries.

Traceback (most recent call last):
  File "/opt/X/current/bin/ldmsd_controller", line 66, in <module>
    from ldmsd.ldmsd_communicator import LDMSD_Request, LDMSD_Req_Attr
  File "/opt/X/current/lib/python3.8/site-packages/ldmsd/ldmsd_communicator.py", line 54, in <module>
    from ovis_ldms import ldms
ImportError: /opt/X/current/lib/python3.8/site-packages/ovis_ldms/ldms.so: undefined symbol: _Py_tracemalloc_config

LDMS 4.4.2, python3.8, cython3-3.8 in centos8.

**Comment by tom95858** [comment]
@baallan, this seems like a forum question, not an issue. This seems to be a Python versioning issue, not an LDMS issue. Please reopen if needed, but with a description of a specific LDMS problem.
