### ISSUE TITLE
log_level command for a subsystem does not work before the subsystem is loaded

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ldms#1343]
The log_level command for a subsystem does not work before the subsystem is registered (plugin loaded), which makes it impossible to create prolog scripts setting subsystem log levels that are independent of the plugin configurations tested.

This is an implementation artifact that is easily remedied by adjustment to the functions implementing register and set_level for subsystems.

**Comment by tom95858** [comment]
Please re-open if needed.
