### ISSUE TITLE
Issues with ldms_xprt_new_with_auth() Function 

### ISSUE THREAD

**Issue by Snell1224** [ovis-hpc/ldms#1428]
When trying to install Darshan against the most recent version of LDMS, I received a error with ``ldms_xprt_new_with_auth()`` (under `ovis/ldms/src/ldmsd/ldmsd_stream.c`). 

This issue has occurred before a year or so ago due to the ``ldms_log_fn_t log_fn`` being removed and all affected codes were updated to reflect this change.

Unless the ``ldms_log_fn_t log_fn`` argument has been put back in, I believe we'll need to reinstall LDMS with the correct version that includes this function.
    
LDMS Installation Version
```$ ldmsd -V
   LDMSD Version: 4.4.3_0toss
   LDMS Protocol Version: 4.2.0.0
   LDMSD Plugin Interface Version: 3.2.2.0
   git-SHA: abea7742e77a5e5c303ffafde6c69c849051bd51
```

OUTPUT ERROR:
```../../../darshan-runtime/lib/darshan-ldms.c:75:51: warning: passing argument 2 of 'ldms_xprt_new_with_auth' from incompatible pointer type [-Wincompatible-pointer-types]
   75 |         dC.ldms_g = ldms_xprt_new_with_auth(xprt, auth, NULL);
      |                                                   ^~~~
      |                                                   |
      |                                                   const char *
In file included from ../../../darshan-runtime/lib/darshan-ldms.h:12,
                 from ../../../darshan-runtime/lib/darshan-ldms.c:17:
/usr/include/ldms/ldms.h:633:69: note: expected 'ldms_log_fn_t' {aka 'void (*)(const char *, ...)'} but argument is of type 'const char *'
  633 | ldms_t ldms_xprt_new_with_auth(const char *xprt_name, ldms_log_fn_t log_fn,
      |                                                       ~~~~~~~~~~~~~~^~~~~~
.....
```

**Comment by Snell1224** [comment]
@nichamon Thank you for the information! I will modify my code so it reflects the installed 4.4.3 version on our machines until version 4.5.1 is released. Do we know when this will be released? 

I only ask because there are a handful of programs that use the version of  ‘’xprt_new_with_auth()’’  from top of tree. Their programs will be affected when they run on this production machine and I would like to let them know how long until the newest release of LDMS can be installed.

**Comment by tom95858** [comment]
This has been resolved
