### ISSUE TITLE
ldmsd_decomposition.man needs update to document functional operations

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ldms#1429]
The new functional operations and related syntax (group, limit, index, etc.) need to be documented in ldmsd_decomposition.man.

**Comment by tom95858** [comment]
@narategithub we should get this done for 4.4.5

**Comment by narategithub** [comment]
> @narategithub we should get this done for 4.4.5

I'll add this on my list.

**Comment by emdonat** [comment]
Resolved in pr #1515
