### ISSUE TITLE
ldmsd -t exits unless a log to be truncated is preexisting.

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ldms#1443]
in b4.4 at least starting with ldmsd -t generates 'Could not truncated the log file named '*'. errno=2

**Comment by baallan** [comment]
@tom95858 or @nichamon please review

**Comment by tom95858** [comment]
It looks like this is an issue where the implementation does not check if the file already exists.

**Comment by baallan** [comment]
fixed in #1488

**Comment by emdonat** [comment]
Resolved with #1488
