### ISSUE TITLE
Rename the "OVIS-4" branch to "main"

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ldms#1452]
I would like to see us rename the "OVIS-4" branch to be named "main". This would align us with pretty standard git branch naming practices.

Github makes it possible to do this through the repositories "Settings" page.

On the "Settings" page is a "Default branch" section.

To the right of the text box containing the name of the default branch is a button that looks like a pencil. The tool-tip for that button is "Rename branch".

Click on the pencil button.

Enter new branch name of "main".

Github will automatically fix up any outstanding pull requests to point to the new name.

The only other thing to do is to let the developer community know about the change so they can update their local practices to use "main".

**Comment by baallan** [comment]
See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch for handling expected side effects.

**Comment by emdonat** [comment]
This work has been completed.
