### ISSUE TITLE
SOS store failure on schema kills entire daemon

### ISSUE THREAD

**Issue by bschwal** [ovis-hpc/ldms#1524]
Just wanted to open up a discussion about this. Currently if a schema changes and SOS is not able to store because of the change the entire LDMS daemon will fail. A daemon not running is a surefire way to alert the user that something is wrong but perhaps we want to add an option to the sos_store configuration to allow the schema store to fail, remove that storage policy, log an error, and let the daemon continue. This way we could still get the data from other schemas and ldms would continue working, albeit in a degraded state.

**Comment by tom95858** [comment]
@bschwal please be more specific. What does "fail" mean? Does it crash, does it exit, does it log an error?

**Comment by bschwal** [comment]
The daemon will throw an assert, the daemon will stop, and a coredump will be written.

**Comment by bschwal** [comment]
No log messages other than "an assert failed in sos_store.c" are written.

**Comment by tom95858** [comment]
Ben, please help me here. "an assert failed ..." does not exist. What assert? What line number? Where is the core dump? What machine?

**Comment by bschwal** [comment]
Sorry I thought this was an intended design that we talked about a while ago so I wanted to discuss design changes rather than stating its an issue. I wasn't giving much info about the assert as a result. Here's the full story: 

The filesingle schema changed while a store for it was running on daemons on our cluster Shirley (I put an example coredump in your home dir). The meaningful lines from the gdb of the corefile are: 

#4  0x00007f4fbc4d2804 in __store_metric (obj=0x7f4e30b93780, attr=0x7f4e300589a0, set=0x7f4e244ce2c0, metric_type=LDMS_V_S64, mval=0x7f4fc50567d8, count=0)
    at ../../../../ldms/src/store/store_sos.c:1044
1044                            assert(0);
(gdb) up
#5  0x00007f4fbc4d36d2 in __store_basic (si=0x7f4e30b910b0, s=0x7f4e244ce2c0, metric_arry=0x7f4e30b90b30, metric_count=347)
    at ../../../../ldms/src/store/store_sos.c:1305
1305                    attr = __store_metric(obj, attr, s, metric_type, mval, count);
(gdb) p obj->schema->data->name
$1 = "filesingle_{CLUSTER}", '\000' <repeats 229 times>

The only output to logfile in this scenario is this line:
ldmsd: ../../../../ldms/src/store/store_sos.c:1044: __store_metric: Assertion `0' failed.

I think this needs better error handling regardless of other points I made about not having the entire daemon stop. But I think we should explore other ways to report this error to users (or work around it with a temporary schema) and keep the daemon running.

**Comment by tom95858** [comment]
@bschwal awesome, thanks for the core dump. @nichamon has a pull request outstanding to convert these asserts to log messages. The question is what _should_ we do? Build a new schema? Seems like there would be lots of downstream analysis issues with that approach. Why did the schema change? It looks to me like there were dozens of coredumps. Basically, two core dumps (two minutes apart) ever hour. Seems like there may be some configuration issue?

**Comment by tom95858** [comment]
@bschwal could you please close this if it is resolved by @nichamon patch?

**Comment by bschwal** [comment]
Closed by a patch 1532.
