### ISSUE TITLE
ldmsd should enforce plugin API semantics

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ldms#50]
ldmsd should enforce the sematics chosen for the plugin API.

For instance, one rule in ldms is that every sampler plugin _must_ have config() called before the sampler is started.  It should be fairly simple to add a flag somewhere like struct ldms_plugin_cfg that tracks when config() has been successfully called.  Then ldmsd can issue an error any time a command is issued to start a plugin that has not been configured.

Right now ldmsd fully permits starting a plugin without configuring it first.

**Comment by morrone** [comment]
Not addressed, as far as I can tell.

**Comment by tom95858** [comment]
@morrone, whether config can be called once or multiple times is up to the plugin. Some allow modifications, others do not. Please reopen if you would like to reconsider all of this.

**Comment by morrone** [comment]
I think we should reconsider having essentially no semantics surrounding config(). It just doesn't see like a reasonable API to me.
