### ISSUE TITLE
stream permissions analogous to metric set

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ldms#899]
We can connect a user-owned L2 aggregator to a system-owned L1 aggregator via munge and get copies of sets with permission 644 into our L2 from the L1. The analogous behavior for stream data apparently isn't supported. Specifically:
 *  if I connect to the L1 from my user account with ldmsd_controller and munge and try to stream_client_dump, I get
```
> stream_client_dump
Operation not permitted.
Expecting value: line 1 column 1 (char 0)
```
and ldmsd_controller exits rather than returning a to the prompt, while if I connect ldmsd_controller with ovis, then i get back the expected list of subscriptions. 
 * if i try to subscribe to the L1 streams, from my L2, I get no events.

It seems like we should have permissions fields optionally set by the user publishing the messages the same as  metric sets have permissions. We should perhaps also discuss the admin's ability to override (tighten) permissions when they make subscriptions. The default for event data should probably be analogous to 600.

**Comment by tom95858** [comment]
@baallan please reopen if necessary.
