### ISSUE TITLE
ldms/src/decomp/static/decomp_static.c:956: dcol used uninit

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ldms#981]
The error message in decomp_static appears to have been cloned from the make_rows region but dcol is used uninit afaict, likely leading to confusing or seg faulting messages when debugging configuration errors.

**Comment by tom95858** [comment]
@nichamon, @baallan is this resolved?

**Comment by tom95858** [comment]
@baallan please reopen if necessary.
